---
- name: Configure Raspberry Pi Zero 2W
  hosts: raspberrypi
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Set up cron job for soil moisture data download
      cron:
        name: "Download data"
        minute: "0"
        hour: "6"
        job: "python ${CRON_SCRIPT_PATH}"

    - name: Configure API to start on boot
      systemd:
        name: OpenFlow_api_service
        enabled: yes
        state: started

    - name: Set up TUF updater cron job
      cron:
        name: "TUF update check"
        minute: "0"
        hour: "6"
        job: "/usr/bin/python3 /user/share/OpenFlow/tuf_update_script.py"