---
- name: Configure Raspberry Pi Zero 2W
  hosts: raspberrypi
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - git
        state: present

    - name: Set up cron job for data download
      cron:
        name: "Download data"
        minute: "0"
        hour: "3"
        job: "/usr/bin/python3 /path/to/your/download_script.py"

    - name: Configure API to start on boot
      systemd:
        name: your_api_service
        enabled: yes
        state: started

    - name: Set up TUF updater cron job
      cron:
        name: "TUF update check"
        minute: "0"
        hour: "4"
        job: "/usr/bin/python3 /path/to/your/tuf_update_script.py"