---
- name: Configure Raspberry Pi Zero 2W
  hosts: raspberrypi
  become: yes
  vars:
    api_service_name: openflow_api_service
    api_script_path: /usr/local/bin/openflow_api.py
    cron_script_path: /usr/local/bin/openflow_cron.py
    SMAP_DB_PATH: os.getenv('OPENFLOW_SMAP_DB_PATH', '/var/lib/openflow/smap_data.db')
    VEGDRI_DB_PATH: os.getenv('OPENFLOW_VEGDRI_DB_PATH', '/var/lib/openflow/vegdri_data.db')
    earthdata_username: "{{ lookup('env', 'EARTHDATA_USERNAME') }}"
    earthdata_password: "{{ lookup('env', 'EARTHDATA_PASSWORD') }}"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - git
          - sqlite3
        state: present

    - name: Install required Python packages
      pip:
        name:
          - bottle
          - waitress
          - aiohttp
          - apscheduler
          - earthaccess

    - name: Create directory for SQLite database
      file:
        path: /var/lib/openflow
        state: directory
        mode: '0755'
    
    - name: Set up SMAP SQLite database
      command: sqlite3 {{ SMAP_DB_PATH }} "CREATE TABLE IF NOT EXISTS smap_data (date TEXT, location TEXT, value REAL);"
      args:
        creates: "{{ SMAP_DB_PATH }}"

    - name: Set up VegDRI SQLite database
      command: sqlite3 {{ VEGDRI_DB_PATH }} "CREATE TABLE IF NOT EXISTS vegdri_data (date TEXT, location TEXT, value REAL);"
      args:
        creates: "{{ VEGDRI_DB_PATH }}"

    - name: Copy API script
      copy:
        src: scripts/openflow_api.py
        dest: "{{ api_script_path }}"
        mode: '0755'

    - name: Copy cron script
      copy:
        src: scripts/openflow_cron.py
        dest: "{{ cron_script_path }}"
        mode: '0755'

    - name: Set up OpenFlow's environment variables
      lineinfile:
        path: /etc/environment
        line: "{{ item }}"
      loop:
        - "EARTHDATA_USERNAME={{ earthdata_username }}"
        - "EARTHDATA_PASSWORD={{ earthdata_password }}"
        - "VEGDRI_DB_PATH" = {{ VEGDRI_DB_PATH }}
        - "SMAP_DB_PATH" = {{ SMAP_DB_PATH }}

    - name: Set up cron job for data download (SMAP + VegDRI)
      cron:
        name: "Download SMAP and VegDRI data"
        minute: "0"
        hour: "6"
        job: "python3 {{ cron_script_path }}"
    
    - name: Create systemd service file for API
      template:
        src: config/openflow_api.service.j2
        dest: /etc/systemd/system/{{ api_service_name }}.service
        mode: '0644'
    
    - name: Configure API to start on boot
      systemd:
        name: OpenFlow_api_service
        enabled: yes
        state: started
        daemon_reload: yes
