name: Build Raspberry Pi Golden Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare custom stage
      run: |
        mkdir -p custom-stage/01-ansible-config
        cp ${GITHUB_WORKSPACE}/ansible/ansible-playbook.yml ${GITHUB_WORKSPACE}/custom-stage/01-ansible-config/ansible-playbook.yml

        if [ $? -ne 0 ]; then
          echo "Error: File not copied!"
          exit 1
        fi

        cat <<EOF > ${GITHUB_WORKSPACE}/custom-stage/01-ansible-config/00-run.sh
        #!/bin/bash -e
        on_chroot <<INNER_EOF
          apt-get update
          apt-get install -y ansible
          ansible-playbook /custom-stage/01-ansible-config/ansible-playbook.yml
        INNER_EOF
        EOF

        chmod +x ${GITHUB_WORKSPACE}/custom-stage/01-ansible-config/00-run.sh

        cat <<EOF > ${GITHUB_WORKSPACE}/custom-stage/prerun.sh
        #!/bin/bash -e
        if [ ! -d "\${ROOTFS_DIR}" ]; then
          copy_previous
        fi
        EOF

        chmod +x ${GITHUB_WORKSPACE}/custom-stage/prerun.sh

    - name: Build Raspberry Pi Image
      uses: usimd/pi-gen-action@v1.9.0
      with:
        image-name: custom-raspberrypi-image
        stage-list: stage0 stage1 stage2 custom-stage
        enable-ssh: 1
        hostname: openflowserver
        username: openflowuser
        password: ${{ secrets.RPI_PASSWORD }}
        locale: en_US.UTF-8
        timezone: America/Denver
        keyboard-keymap: us
        keyboard-layout: English (US)
        pi-gen-version: arm64
        compression: zip
        verbose-output: true

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.build.outputs.image-path }}