name: Build Raspberry Pi Golden Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SCRIPT_PATH: /usr/share/openflow/cronscript.sh

jobs:
  pi-gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare custom stage
      run: |
        mkdir -p custom-stage &&
        {
        cat > custom-stage/00-run-chroot.sh <<-EOF
        #!/bin/bash
        echo "*/5 * * * * ${SCRIPT_PATH}" >> /etc/crontab
        EOF
        } &&
        chmod +x custom-stage/00-run-chroot.sh &&
        touch custom-stage/prerun.sh

    - name: Build Raspberry Pi Image
      uses: usimd/pi-gen-action@v1.9.0
      with:
        image-name: custom-raspberrypi-image
        stage-list: stage0 stage1 stage2 custom-stage
        enable-ssh: 1
        hostname: openflowserver
        username: openflowuser
        password: ${{ secrets.RPI_PASSWORD }}
        locale: en_US.UTF-8
        timezone: America/Denver
        keyboard-keymap: us
        keyboard-layout: English (US)
        pi-gen-version: arm64
        compression: zip
        verbose-output: true
      id: build

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.build.outputs.image-path }}