name: Build Raspberry Pi Golden Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SCRIPT_PATH: /usr/share/openflow/cronscript.sh

jobs:
  pi-gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare custom stage
      run: |
        mkdir -p custom-cron-stage
        cat > custom-cron-stage/00-run-chroot.sh << 'EOF'
        #!/bin/bash
        set -e

        # Install Ansible
        apt-get update
        apt-get install -y ansible

        # Copy Ansible playbook from the repository to the image
        cp -r /ansible /root/ansible

        # Run Ansible playbook
        ansible-playbook /root/ansible/ansible-playbook.yml
        EOF

        chmod +x custom-cron-stage/00-run-chroot.sh

        cat > custom-cron-stage/prerun.sh << 'EOF'
        #!/bin/bash -e
        if [ ! -d "${ROOTFS_DIR}" ]; then
          copy_previous
        fi
        EOF

        chmod +x custom-cron-stage/prerun.sh

    - name: Build Raspberry Pi Image
      uses: usimd/pi-gen-action@v1.9.0
      id: build
      with:
        image-name: openflow-server-image
        stage-list: stage0 stage1 stage2 ./custom-cron-stage
        enable-ssh: 1
        hostname: openflowserver
        username: openflowuser
        password: ${{ secrets.RPI_PASSWORD }}
        locale: en_US.UTF-8
        timezone: America/Denver
        keyboard-keymap: us
        keyboard-layout: English (US)
        pi-gen-version: arm64
        compression: zip
        verbose-output: true
        wpa-country: 'US'
        wpa-essid: ${{ secrets.WPA_SSID }}
        wpa-password: ${{ secrets.WPA_PASSWORD }}

    - name: Upload image artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: custom-cron-raspios
        path: ${{ steps.build.outputs.image-path }}