name: Build Raspberry Pi Golden Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SCRIPT_PATH: /usr/share/openflow/cronscript.sh

jobs:
  pi-gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare custom stage
      run: |
        mkdir -p custom-cron-stage &&
        {
          cat > custom-cron-stage/00-run-chroot.sh << EOF
          #!/bin/bash
          set -e

          # Add a cron job to run a script every day at midnight
          echo "0 0 * * * root $SCRIPT_PATH" > /etc/cron.d/daily-task
          # Create the script that will be run by the cron job
          cat > /usr/local/bin/daily-task.sh << EOT
          #!/bin/bash
          echo "Daily task executed at \$(date)" >> /var/log/daily-task.log
          EOT

          # Make the script executable
          chmod +x /usr/local/bin/daily-task.sh
          EOF

          # Make the script executable
          chmod +x custom-cron-stage/00-run-chroot.sh

          # Create the prerun.sh script
          cat > custom-cron-stage/prerun.sh << EOF
          #!/bin/bash -e
          if [ ! -d "${ROOTFS_DIR}" ]; then
            copy_previous
          fi
          EOF
        } &&
        chmod +x custom-cron-stage/prerun.sh

    - name: Build Raspberry Pi Image
      uses: usimd/pi-gen-action@v1.9.0
      with:
        image-name: custom-raspberrypi-image
        stage-list: stage0 stage1 stage2 ./custom-cron-stage
        enable-ssh: 1
        hostname: openflowserver
        username: openflowuser
        password: ${{ secrets.RPI_PASSWORD }}
        locale: en_US.UTF-8
        timezone: America/Denver
        keyboard-keymap: us
        keyboard-layout: English (US)
        pi-gen-version: arm64
        compression: zip
        verbose-output: true

    - name: Upload image artifact
      uses: actions/upload-artifact@v3
      with:
        name: custom-cron-raspios
        path: ${{ steps.build.outputs.image-path }}