name: Build Raspberry Pi Golden Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' 

    - name: Install Ansible
      run: pip install ansible

    - name: Prepare custom stage
      run: |
        mkdir -p custom-stage/01-ansible-config
        cp ${GITHUB_WORKSPACE}/ansible/ansible-playbook.yml custom-stage/01-ansible-config/ansible-playbook.yml

        if [ -f custom-stage/01-ansible-config/ansible-playbook.yml ]; then
          echo "File copied successfully!"
          ls -l custom-stage/01-ansible-config/ansible-playbook.yml
        else
          echo "Error: File not copied!"
          exit 1
        fi
        
        cat << EOF > custom-stage/01-ansible-config/00-run-chroot.sh
        #!/bin/bash -e
        apt-get update
        apt-get install -y ansible
        mkdir -p /ansible
        cp /custom-stage/01-ansible-config/ansible-playbook.yml /ansible/ansible-playbook.yml
        ansible-playbook /ansible/ansible-playbook.yml
        EOF
        
        chmod +x custom-stage/01-ansible-config/00-run-chroot.sh
        
        cat << EOF > custom-stage/prerun.sh
        #!/bin/bash -e
        if [ ! -d "\${ROOTFS_DIR}" ]; then
          copy_previous
        fi
        EOF
        
        chmod +x custom-stage/prerun.sh

    - name: Build Raspberry Pi Image
      uses: usimd/pi-gen-action@v1.9.0
      with:
        image-name: custom-raspberrypi-image
        stage-list: stage0 stage1 stage2 custom-stage
        enable-ssh: 1
        hostname: openflowserver
        username: openflowuser
        password: ${{ secrets.RPI_PASSWORD }}
        locale: en_US.UTF-8
        timezone: America/Denver
        keyboard-keymap: us
        keyboard-layout: English (US)
        pi-gen-version: arm64
        compression: zip
        verbose-output: true

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.build.outputs.image-path }}