name: Build Raspberry Pi Golden Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' 

    - name: Install Ansible
      run: pip install ansible

    - name: Create custom stage for cron job
      run: |
        mkdir -p cron-stage &&
        {
        cat > cron-stage/prerun.sh <<-EOF
        #!/bin/bash
        echo "0 0,12 * * * python ${CRON_SCRIPT_PATH}" >> /etc/cron.d/openflow_cron_job
        EOF
        } &&
        chmod +x cron-stage/prerun.sh

    - name: Build Raspberry Pi Image
      uses: usimd/pi-gen-action@v1.9.0
      with:
        image-name: custom-raspberrypi-image
        stage-list: stage0 stage1 stage2 ./cron-stage
        enable-ssh: 1
        hostname: openflowserver
        username: openflowuser
        password: ${{ secrets.RPI_PASSWORD }}
        locale: en_US.UTF-8
        timezone: America/Denver
        keyboard-keymap: us
        keyboard-layout: English (US)
        pi-gen-version: arm64
        compression: zip
        verbose-output: true

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.build.outputs.image-path }}